sonar.projectKey=Mattair39_FitFlow
sonar.organization=mattair39
sonar.projectName=FitFlow

sonar.sources=fitFlow/backend/app,fitFlow/front-react/doc/src
sonar.tests=fitFlow/tests/backend,fitFlow/front-react/doc/src

sonar.exclusions=fitFlow/backend/app/debug_plan_data.py,fitFlow/backend/app/migration_add_plan_date.py,fitFlow/front-react/doc/src/**/*.test.jsx,fitFlow/front-react/doc/src/**/*.test.js,**/node_modules/**,**/dist/**,**/reports/**,**/__pycache__/**
sonar.test.inclusions=fitFlow/tests/backend/**/*.py,fitFlow/front-react/doc/src/**/*.test.jsx,fitFlow/front-react/doc/src/**/*.test.js

sonar.python.coverage.reportPaths=fitFlow/reports/backend/coverage.xml
sonar.javascript.lcov.reportPaths=fitFlow/front-react/doc/reports/frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
