sonar.projectKey=Mattair39_FitFlow
sonar.organization=mattair39
sonar.projectName=FitFlow

sonar.sources=fitFlow/backend,fitFlow/front-react,fitFlow/k8s

sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/reports/**,**/dist/**,fitFlow/backend/app/debug_plan_data.py,fitFlow/backend/app/migration_add_plan_date.py,fitFlow/front-react/doc/src/**/*.test.jsx,fitFlow/front-react/doc/src/test/**
sonar.coverage.exclusions=fitFlow/backend/app/api/**,fitFlow/backend/app/database/**,fitFlow/backend/Dockerfile,fitFlow/front-react/Dockerfile,fitFlow/front-react/nginx.conf,fitFlow/k8s/**,fitFlow/front-react/doc/src/**/*.test.jsx,fitFlow/front-react/doc/src/test/**,fitFlow/front-react/doc/src/main.jsx

sonar.python.version=3.11
sonar.python.coverage.reportPaths=fitFlow/reports/backend/coverage.xml
sonar.javascript.lcov.reportPaths=fitFlow/front-react/doc/reports/frontend/coverage/lcov.info
