apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitflow-backend
  namespace: fitflow
  labels:
    app: fitflow-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fitflow-backend
  template:
    metadata:
      labels:
        app: fitflow-backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fitflow-backend
          image: mattair39/fitflow-backend:v1
          imagePullPolicy: Always
          env:
            - name: FITFLOW_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fitflow-secrets
                  key: FITFLOW_SECRET_KEY
                  optional: true
            - name: FITFLOW_DATABASE_URL
              value: sqlite:////tmp/fitflow.db
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
